#!/bin/bash

# Script para demonstrar o fluxo completo de cadastro
# Mostra como o CPF é usado como username e salvo no campo email

echo "🔄 Demonstração do Fluxo de Cadastro"
echo "====================================="
echo ""

echo "📱 FRONTEND (Tela de Registro):"
echo "  - Usuário informa:"
echo "    • Email: joao@exemplo.com"
echo "    • CPF: 123.456.789-00"
echo "    • Password: MinhaSenha123!"
echo "    • Password Repeat: MinhaSenha123!"
echo ""

echo "📤 FRONTEND envia para BFF:"
echo "  POST /api/v1/wallets"
echo "  {"
echo "    \"username\": \"12345678900\",     // CPF limpo"
echo "    \"email\": \"joao@exemplo.com\",   // Email do usuário"
echo "    \"password\": \"MinhaSenha123!\","
echo "    \"password_repeat\": \"MinhaSenha123!\""
echo "  }"
echo "  // ✅ Email agora é enviado e salvo"
echo ""

echo "🔧 BFF processa:"
echo "  - Valida CPF (12345678900)"
echo "  - Valida senha"
echo "  - Cria wallet no LNBits"
echo "  - Salva no banco SQLite"
echo ""

echo "💾 BANCO DE DADOS (tabela wallets):"
echo "  +----+----------------+------------------+------------------+------------+"
echo "  | id | cpf            | email            | password         | wallet_id  |"
echo "  +----+----------------+------------------+------------------+------------+"
echo "  | 1  | 12345678900    | joao@exemplo.com | hash_da_senha    | abc123...  |"
echo "  +----+----------------+------------------+------------------+------------+"
echo "  // ✅ CPF salvo no campo 'cpf'"
echo "  // ✅ Email salvo no campo 'email'"
echo ""

echo "🔍 LOGIN posterior:"
echo "  POST /api/v1/login"
echo "  {"
echo "    \"email\": \"12345678900\",        // CPF (não email real)"
echo "    \"password\": \"MinhaSenha123!\""
echo "  }"
echo ""

echo "✅ PROBLEMAS RESOLVIDOS:"
echo "  1. Email do usuário é salvo corretamente"
echo "  2. CPF e email têm campos separados"
echo "  3. Ambos os dados estão disponíveis para funcionalidades futuras"
echo ""

echo "💡 MELHORIAS IMPLEMENTADAS:"
echo "  1. ✅ CreateWalletRequest agora inclui email"
echo "  2. ✅ Campo 'cpf' separado do campo 'email' no banco"
echo "  3. ✅ Estrutura clara e organizada"
echo "  4. ✅ Login funciona com CPF, email disponível para outras funcionalidades"
echo ""

echo "🧪 Para testar o fluxo real:"
echo "  1. Iniciar backend: ./bff-luma"
echo "  2. Criar usuário via frontend ou API"
echo "  3. Verificar banco: sqlite3 bff_luma.db"
echo "  4. Ver dados: SELECT * FROM wallets;"
